apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      annotations:
        # WARNING: This simulates the service account being exposed via an annotation.
        cloud.google.com/service_account: "INVALID@prod-project-id.iam.gserviceaccount.com"
    spec:
      containers:
      - name: echo-server
        # un-comment one image: for use
        image: docker.io/captjohnwickprice/bh-aisec-project1-attp-echo-server@sha256:49f16b8347e1dde92544ad4dc1d90ad7eefa0b8e55aadbe15fa1e1af39f7371a
        #image: docker.io/INVALID/bh-aisec-project1-INVALID-echo-server@sha256:49f16b8347e1dde92544ad4dc1d90ad7eefa0b8e55aadbe15fa1e1af39f7371a
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort # Exposes the service on a port on each node's IP
