apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      annotations:
        # WARNING: This simulates the service account being exposed via an annotation.
        cloud.google.com/service_account: "name@prod-project-id.iam.gserviceaccount.com"
    spec:
      containers:
      - name: echo-server
        image: docker.io/lmrs2/bh-aisec-project1-echo-server@sha256:7e0c03e174f7f64ab5c4a1ce9cabd3e01d017d73a802597ad2b4da8f846e6a58
        ports:
        - containerPort: 8081
