name: Requirements generation

on:
  workflow_dispatch:

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip-tools
        run: |
          pip install pip-tools

      - name: Generate requirements.txt
        run: |
          pip-compile --generate-hashes --output-file=images/echo-server/install/requirements_predict.txt --strip-extras images/echo-server/install/requirements_predict.in

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: requirement_predict.txt

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: images/echo-server/install/requirements_predict.txt
